exemptions = set("""
model-principal-components/train.rst
model-principal-components/predict.rst
model-libsvm/train.rst
model-libsvm/predict.rst
model-libsvm/test.rst
model-libsvm/score.rst
model/rename.rst
model-random_forest/train.rst
model-random_forest/predict.rst
model-random_forest/test.rst
frame-vertex/drop_duplicates.rst
frame-vertex/add_vertices.rst
graph-/vertex_count.rst
graph-/export_to_titan.rst
graph-/_info.rst
graph-/edge_count.rst
graph-/define_edge_type.rst
graph-/define_vertex_type.rst
graph-/ml/kclique_percolation.rst
model-lda/train.rst
model-lda/predict.rst
model-svm/train.rst
model-svm/predict.rst
model-svm/test.rst
model-linear_regression/train.rst
model-linear_regression/predict.rst
model-logistic_regression/train.rst
model-logistic_regression/predict.rst
model-logistic_regression/test.rst
graph-titan/graph_clustering.rst
graph-titan/query/gremlin.rst
graph-titan/query/recommend.rst
graph-titan/ml/belief_propagation.rst
graph-titan/sampling/assign_sample.rst
graph-titan/sampling/vertex_sample.rst
frame-/load.rst
frame-/rename_columns.rst
frame-/collaborative_filtering.rst
frame-/loopy_belief_propagation.rst
frame-/filter.rst
frame-/join.rst
frame-/label_propagation.rst
frame-edge/add_edges.rst
graph/graphx_connected_components.rst
graph/graphx_triangle_count.rst
graph/annotate_degrees.rst
graph/graphx_pagerank.rst
graph/copy.rst
graph/clustering_coefficient.rst
graph/annotate_weighted_degrees.rst
graph/ml/kclique_percolation.rst
graph/ml/belief_propagation.rst
model-k_means/train.rst
model-k_means/predict.rst
model-naive_bayes/train.rst
model-naive_bayes/predict.rst
**ON**frame/ecdf.rst
frame/export_to_hive.rst
frame/covariance_matrix.rst
frame/cumulative_percent.rst
frame/bin_column_equal_depth.rst
frame/group_by.rst
frame/drop_duplicates.rst
frame/column_summary_statistics.rst
frame/quantiles.rst
frame/export_to_jdbc.rst
frame/histogram.rst
frame/entropy.rst
frame/correlation_matrix.rst
frame/categorical_summary.rst
frame/drop_columns.rst
frame/assign_sample.rst
frame/covariance.rst
frame/flatten_column.rst
frame/copy.rst
frame/count_where.rst
frame/dot_product.rst
frame/export_to_hbase.rst
frame/tally.rst
frame/sort.rst
frame/cumulative_sum.rst
frame/classification_metrics.rst
frame/rename.rst
frame/tally_percent.rst
frame/column_median.rst
frame/unflatten_column.rst
frame/top_k.rst
frame/bin_column.rst
frame/sorted_k.rst
frame/export_to_json.rst
frame/add_columns.rst
frame/correlation.rst
frame/column_mode.rst
frame/export_to_csv.rst
frame/bin_column_equal_width.rst
""".splitlines())
